version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    env_file:
      - .env
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./sql/init.sql:/init.sql

  db_init:
    image: mcr.microsoft.com/mssql-tools
    container_name: db_init
    depends_on:
      - sqlserver
    entrypoint: >
      bash -c "
        echo 'Esperando a que SQL Server esté listo...' &&
        sleep 20 &&
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P '${DB_PASSWORD}' -i /init.sql
      "
    volumes:
      - ./sql/init.sql:/init.sql

  app:
    build: .
    container_name: backend-service
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=sqlserver
      - DB_NAME=clientes_db
      - DB_PORT=1433
    depends_on:
      - sqlserver
      - db_init
    volumes:
      - .:/app
      - ./input:/app/input


volumes:
  mssql_data:
