version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Password123"
      ACCEPT_EULA: "Y"
    networks:
      - app-net

  app:
    build: .
    container_name: backend-service
    depends_on:
      - db
    environment:
      DB_USER: sa
      DB_PASSWORD: YourStrong@Password123
      DB_NAME: clientes_db
      DB_SERVER: db
      DB_PORT: 1433
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - app-net

networks:
  app-net:
 
